version: 2.1

workflows:
  version: 2
  test_build:
    jobs:
      - build_and_test:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build_and_test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/


jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Cenerate crypto test materials
          command: |
            ls -l
            export ORIGIN=${PWD}
            bash ./generate_crypto.sh
            cd ${ORIGIN}
            mkdir -p tests/fixtures/dynamic
            sudo cp ${HOME}/export/* tests/fixtures/dynamic/
            sudo chown -R `whoami` ${HOME}
      - run:
          name: Install deps and run unit and integration tests
          command: |
            pip3 install -r requirements-develop.txt
            pip3 install -r requirements-test.txt
            pip3 install .
            python3 -m py.test --cov=dane_discovery --cov-report term-missing
      - run:
          name: Test building docs
          command: |
            pip3 install -r requirements-doc.txt
            cd docs
            make html
      - run:
          name: Trigger build in RTD
          command: |
            curl -X POST -d "branches=${CIRCLE_BRANCH}" -d "token=${RTD_TOKEN}" ${RTD_URL}
  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Write PyPI config
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = __token__" >> ~/.pypirc
            echo -e "password = ${PYPI_TOKEN}" >> ~/.pypirc
      - run:
          name: Build sdist, wheel
          command: |
            python setup.py sdist
            python setup.py bdist_wheel
      - run:
          name: Upload to pypi
          command: |
            pip3 install twine
            twine upload dist/*
